apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfgmap
  namespace: mattermost
data:
  file-from-cfgmap: |
    max_connections = 300
    listen_addresses = '*'
    fsync = off
    full_page_writes = off
    default_text_search_config = 'pg_catalog.english'
    commit_delay=1000
    logging_collector=off
