apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: arm64v8/postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 1500m
            memory: 500Mi
        env:
            - name: POSTGRES_PASSWORD
              value: "keycloak"
            - name: POSTGRES_USER
              value: "keycloak"
            - name: POSTGRES_DB
              value: "keycloak"
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresqldb
      volumes:
      - name: postgresqldb
        hostPath:
          path: /opt/data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - kind-worker3
