{{- if .Values.applications.kyverno.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: '*'
    helm:
      values: |
        replicaCount: 3
        config:
          resourceFilters: []
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
{{- end -}}
