{{- if .Values.applications.argocd.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: ingress-nginx
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argocd
            io.cilium.k8s.policy.serviceaccount: argocd-server
        - matchLabels:
            app.kubernetes.io/name: argocd-repo-server
            k8s:io.kubernetes.pod.namespace: argocd
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: argocd
            io.cilium.k8s.policy.serviceaccount: argocd-server
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd
  namespace: argocd
specs:
  - endpointSelector: {}
    ingress:
      - fromEndpoints:
          - matchLabels: {}
    egress:
      - toEndpoints:
          - matchLabels: {}
  - endpointSelector:
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: argocd-server
    ingress:
      - fromEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: ingress-nginx
              io.cilium.k8s.policy.serviceaccount: ingress-nginx
    egress:
      - toEntities:
          - kube-apiserver
          - world
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: ingress-nginx
              io.cilium.k8s.policy.serviceaccount: ingress-nginx
  - endpointSelector:
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: argocd-application-controller
    egress:
      - toEntities:
          - kube-apiserver
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: argocd-repo-server
    egress:
      - toEntities:
          - world
      - toEndpoints:
          - matchLabels:
              k8s:io.kubernetes.pod.namespace: ingress-nginx
              io.cilium.k8s.policy.serviceaccount: ingress-nginx
{{- end -}}
