apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gitea
  namespace: gitea
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gitea-server
  namespace: gitea
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: gitea
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: ingress-nginx
        io.cilium.k8s.policy.serviceaccount: ingress-nginx
