{{- if .Values.applications.gitea.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gitea
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: ingress-nginx
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: gitea
        app.kubernetes.io/name: gitea
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: gitea
  namespace: gitea
specs:
  - endpointSelector: {}
    ingress:
    - fromEndpoints:
      - matchLabels: {}
    egress:
    - toEndpoints:
      - matchLabels: {}
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: gitea
    ingress:
    - fromEndpoints:
      - matchLabels:
          k8s:io.kubernetes.pod.namespace: ingress-nginx
          io.cilium.k8s.policy.serviceaccount: ingress-nginx
{{- end -}}
