apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: ingress-nginx
  ingress:
  - fromEntities:
    - host
    - remote-node
  egress:
  - toEntities:
    - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-nginx-admission
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: ingress-nginx-admission
  egress:
  - toEntities:
    - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ingress-nginx-default-backend
  namespace: ingress-nginx
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: ingress-nginx-backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        io.cilium.k8s.policy.serviceaccount: ingress-nginx
