apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keycloak
  namespace: keycloak
spec:
  endpointSelector: {}
  ingress:
  - fromEndpoints:
    - matchLabels: {}
  egress:
  - toEndpoints:
    - matchLabels: {}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keycloak-server
  namespace: keycloak
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: keycloak
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: ingress-nginx
        io.cilium.k8s.policy.serviceaccount: ingress-nginx
  egress:
  - toCIDR:
    - 230.0.0.4/32
