apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost-team-edition
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.mattermost.com
    chart: mattermost-team-edition
    targetRevision: '*'
    helm:
      values: |
        image:
          repository: bmutziu/mattermost-team-linux
          tag: 7.4.0-arm64
        ingress:
          enabled: true
          path: /
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - mattermost.kind.cluster
          tls:
            - secretName: mattermost.kind.cluster
              hosts:
                - mattermost.kind.cluster
        externalDB:
          enabled: true
          externalDriverType: "postgres"
          externalConnectionString: "mmuser:mostest@postgresql-mm-np:5432/mattermost_test?sslmode=disable&connect_timeout=10"
        mysql:
          enabled: false
        extraVolumes:
          - name: opt-ca-certificates
            hostPath:
              path: /opt/ca-certificates/root-ca.pem
              type: File
        extraVolumeMounts:
          - name: opt-ca-certificates
            mountPath: /etc/ssl/certs/root-ca.pem
            readOnly: true
        securityContext:
          fsGroup: 2000
          runAsGroup: 2000
          runAsUser: 2000
        config:
          MM_PLUGINSETTINGS_CLIENTDIRECTORY: "./client/plugins"
          MM_SERVICESETTINGS_SITEURL: https://mattermost.kind.cluster
          MM_TEAMSETTINGS_SITENAME: Mattermost on kind.cluster
          MM_GITLABSETTINGS_ENABLE: 'true'
          MM_GITLABSETTINGS_ID: mattermost
          MM_GITLABSETTINGS_SECRET: mattermost-client-secret
          MM_GITLABSETTINGS_AUTHENDPOINT: https://keycloak.kind.cluster/auth/realms/master/protocol/openid-connect/auth
          MM_GITLABSETTINGS_TOKENENDPOINT: https://keycloak.kind.cluster/auth/realms/master/protocol/openid-connect/token
          MM_GITLABSETTINGS_USERAPIENDPOINT: https://keycloak.kind.cluster/auth/realms/master/protocol/openid-connect/userinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
