apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: minio
    targetRevision: '*'
    helm:
      values: |
        mode: standalone
        auth:
          rootUser: root
          rootPassword: root1234
        persistence:
          enabled: true
          size: 500M
        ingress:
          enabled: true
          hostname: minio.kind.cluster
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: ca-issuer
          tls: true
        apiIngress:
          enabled: true
          hostname: minio-api.kind.cluster
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: ca-issuer
          tls: true
        metrics:
          serviceMonitor:
            enabled: true
        podSecurityContext:
          runAsNonRoot: true
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
