apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polaris
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    chart: polaris
    targetRevision: '*'
    helm:
      values: |
        dashboard:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
              - polaris.kind.cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: polaris
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
