apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: '*'
    helm:
      values: |
        installCRDs: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: {{ .Values.prometheus.operator.enabled }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
