{{- if .Values.applications.metallb.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: '*'
    helm:
      values: |
        configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - {{ required ".Values.metallb.start is required" .Values.metallb.start }}-{{ required ".Values.metallb.end is required" .Values.metallb.end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
{{- end -}}
