{{- if .Values.applications.metallb.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: metallb
  namespace: metallb-system
spec:
  endpointSelector:
    matchLabels:
      io.cilium.k8s.policy.serviceaccount: metallb-controller
  egress:
    - toEntities:
        - kube-apiserver
{{- end -}}
