apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: '*'
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
